import { HeaderLayout as _HeaderLayout } from './HeaderLayout';
export const HeaderLayout = _HeaderLayout;
import { HistoryPage as _HistoryPage } from './HistoryPage';
export const HistoryPage = _HistoryPage;
import { InitPage as _InitPage } from './InitPage';
export const InitPage = _InitPage;
import { LoadingPage as _LoadingPage } from './LoadingPage';
export const LoadingPage = _LoadingPage;
import { MainPage as _MainPage } from './MainPage';
export const MainPage = _MainPage;
import { MyPage as _MyPage } from './MyPage';
export const MyPage = _MyPage;
import { Page as _Page } from './Page';
export const Page = _Page;
import { Pages as _Pages } from './Pages';
export const Pages = _Pages;
import { RegistPage as _RegistPage } from './RegistPage';
export const RegistPage = _RegistPage;
import { SearchPage as _SearchPage } from './SearchPage';
export const SearchPage = _SearchPage;
import { SearchResultPage as _SearchResultPage } from './SearchResultPage';
export const SearchResultPage = _SearchResultPage;
import { SetupPage as _SetupPage } from './SetupPage';
export const SetupPage = _SetupPage;
import { SideMenu as _SideMenu } from './SideMenu';
export const SideMenu = _SideMenu;
import { TouchButton as _TouchButton } from './TouchButton';
export const TouchButton = _TouchButton;
import { UserListPage as _UserListPage } from './UserListPage';
export const UserListPage = _UserListPage;
