//@TODO gulp 자동화 수정.
//@TODO TODO목록 자동화
import { InitPage as _InitPage } from './InitPage';
export const InitPage = _InitPage;
import { LoadingPage as _LoadingPage } from './LoadingPage';
export const LoadingPage = _LoadingPage;
import { Page as _Page } from './Page';
export const Page = _Page;
import { Pages as _Pages } from './Pages';
export const Pages = _Pages;
import { RegistPage as _RegistPage } from './RegistPage';
export const RegistPage = _RegistPage;
import { SideMenu as _SideMenu } from './SideMenu';
export const SideMenu = _SideMenu;
import _MenuButton from './MenuButton';
export const MenuButton = _MenuButton;
import _UnlockButton from './UnlockButton';
export const UnlockButton = _UnlockButton;
import _Logo from './Logo';
export const Logo = _Logo;
import _StartButton from './StartButton';
export const StartButton = _StartButton;
import _TextInputLabel from './TextInputLabel';
export const TextInputLabel = _TextInputLabel;
import _TextButton from './TextButton';
export const TextButton = _TextButton;
import _RegistButton from './RegistButton';
export const RegistButton = _RegistButton;
import _HeaderLayout from './HeaderLayout';
export const HeaderLayout = _HeaderLayout;
import _MyPage from './MyPage';
export const MyPage = _MyPage;
import _MainPage from './MainPage';
export const MainPage = _MainPage;
import _UserListPage from './UserListPage';
export const UserListPage = _UserListPage;
import _HistoryPage from './HistoryPage';
export const HistoryPage = _HistoryPage;
import _SetupPage from './SetupPage';
export const SetupPage = _SetupPage;
import _HistoryList from './HistoryList';
export const HistoryList = _HistoryList;
import _SearchPage from './SearchPage';
export const SearchPage = _SearchPage;
import _SearchResultPage from './SearchResultPage';
export const SearchResultPage = _SearchResultPage;
